
import { KioskProvider } from '@/context/KioskProvider'

import './globals.css'
import { Inter } from 'next/font/google'
import Aside from '@/components/Aside'
import ModalView from '@/components/ModalView'
import Steps from '@/components/Steps'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <KioskProvider>

          <div id='___next'>
            <ModalView />

            {children}
          </div>
        </KioskProvider>
      </body>
    </html>
  )
}
